# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto

    patch:
      default:
        target: 80

    changes: false

comment: false

ignore:
  - authn/authenticator_charlatan.go
  - authn/idp_charlatan.go
  - auxillary/server_charlatan.go
  - context/context_charlatan.go
  - env/provider_charlatan.go
  - models/user_charlatan.go
  - ratelimit/provider_charlatan.go
  - service/service_charlatan.go
  - service/response_charlatan.go
